export const APP_ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  dashboardSchedule: '/dashboard/schedule',
  shadowKnifeLinkage: '/shadow-knife-linkage',
  shadowKnifeTaskBoard: '/shadow-knife-linkage/task-board',
  shadowKnifeLengthRules: '/shadow-knife-linkage/length-rules',
  lengthShadowLinkage: '/length-shadow-linkage',
  instrumentFlow: '/instrument-flow',
  instrumentManagement: '/instrument-mgmt',
  statistics: '/statistics',
  statisticsUsageConsumption: '/statistics/usage-consumption',
  statisticsInstrument: '/statistics/instrument',
  systemSettings: '/system-settings',
  systemSettingsUserManagement: '/system-settings/user-management',
  systemSettingsConfiguration: '/system-settings/system-configuration',
  systemSettingsDataBackup: '/system-settings/data-backup',
  systemSettingsOperationLogs: '/system-settings/operation-logs',
  systemSettingsMaintenance: '/system-settings/maintenance',
  oneClickTransfer: '/one-click-transfer',
} as const;
