export const INSTRUMENT_FIELDS = [
  { key: 'type', label: '仪器类型' },
  { key: 'name', label: '仪器名称' },
  { key: 'model', label: '规格型号' },
  { key: 'serialNumber', label: '出厂编号' },
  { key: 'managementNumber', label: '管理编号' },
  { key: 'manufacturer', label: '生产厂家' },
  { key: 'measureRange', label: '测量范围' },
  { key: 'uncertainty', label: '不确定度/准确度等级' },
  { key: 'traceabilityMethod', label: '溯源方式' },
  { key: 'purchaseDate', label: '采购日期' },
  { key: 'enableDate', label: '启用日期' },
  { key: 'calibrationDate', label: '校准日期' },
  { key: 'nextCalibrationDate', label: '复校日期' },
  { key: 'calibrationCycle', label: '校准周期(月)' },
  { key: 'certificateNumber', label: '证书编号' },
  { key: 'calibrationInstitution', label: '校准机构' },
  { key: 'department', label: '使用部门' },
  { key: 'location', label: '存放位置' },
  { key: 'status', label: '仪器状态' },
  { key: 'inOutStatus', label: '领用状态' },
  { key: 'remarks', label: '备注' },
  { key: 'groupName', label: '分组名称' },
  { key: 'groupModel', label: '分组型号' },
  { key: 'groupMeasureRange', label: '分组测量范围' },
];
